//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBox.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compositions
    {
        public Compositions()
        {
            this.Authors = new HashSet<Authors>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Authors> Authors { get; set; }
    }
}
