//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentAspNet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public Incident()
        {
            this.Ispolnitel = new HashSet<Ispolnitel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string DateOfCreation { get; set; }
        public string DateOfShutDown { get; set; }
        public string CauseOfShutDown { get; set; }
    
        public virtual ICollection<Ispolnitel> Ispolnitel { get; set; }
    }
}
