//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentAspNet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispolnitel
    {
        public Ispolnitel()
        {
            this.Incident = new HashSet<Incident>();
            this.Otdel = new HashSet<Otdel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Post { get; set; }
    
        public virtual ICollection<Incident> Incident { get; set; }
        public virtual ICollection<Otdel> Otdel { get; set; }
    }
}
